# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - prefer_single_quotes
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    - avoid_unnecessary_containers
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - curly_braces_in_flow_control_structures
    - prefer_final_locals

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Transforme les avertissements de code inutilisé en erreurs bloquantes
    unused_import: error
    unused_local_variable: error
    unused_element: error
    duplicate_import: error
    # Capture les erreurs de duplication de classes (votre problème récent)
    duplicate_definition: error

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
